### ISSUE TITLE
Missing Example Volumes

### ISSUE THREAD

**Issue by Jdhaworth** [LCSR-SICKKIDS/volumetric_drilling#16]
Hello! I am able to launch the simulator using only the drill with the command:
`~/ambf/bin/lin-x86_64$ ./ambf_simulator --launch_file ~/volumetric_drilling/launch.yaml -l 0
`

However when I try to use the example volumes by appending ",1" or ",2" or ",3" to the end I get a segmentation error and the simulation immediately crashes: (terminal feedback)
`WARNING! CAN'T FIND ANY OBJECTS NAMED: "cameraL" IN GLOBAL MAP
`
`Existing OBJECTS in Map: 1
`
`/ambf/env/cameras/main_camera
`
`WARNING! CAN'T FIND ANY OBJECTS NAMED: "cameraR" IN GLOBAL MAP
`
`Existing OBJECTS in Map: 1
`
`/ambf/env/cameras/main_camera
`
`Found Lib: libdvrk_arm.so
`
`No of dVRK Masters detected: 0
`
`SUCCESFULLY LOADED MATCAP TEXTURE
`
`Segmentation fault (core dumped)
`

I looked into the launch.yaml file which for option "1" is using "ADF/volume_171.yaml". If I open this file it looks like it is trying to load the meshes found in "/meshes/high_res/" or "/meshes/low_res/". However if I look in these folders I only see files related to the drill (which did load successfully) but no meshes for the volume. 

Maybe I am looking in the wrong place, but either way I'm still having trouble loading the example volumes. Let me know if I can provide any more information to help. Thanks!

**Comment by adnanmunawar** [comment]
Hi Jesse, thanks for creating the issue. The `/meshes/high_res` and `meshes/low_res` are indeed for the meshes and not for the volumes. The volumes are located here https://github.com/LCSR-SICKKIDS/volumetric_drilling/tree/master/resources/volumes .

In terms of the Segfault. Can you please try this branch:

https://github.com/adnanmunawar/volumetric_drilling/tree/study-gui

You can follow these steps:

```
mkdir ~/test_ws && cd ~/test_ws
git clone https://github.com/adnanmunawar/volumetric_drilling
cd ~/test_ws/volumetric_drilling
git checkout -b study_gui origin/study-gui
```
Then build the new branch, like this:

```
cd ~/test_ws/volumetric_drilling
mkdir build && cd build && cmake .. && make
```

Finally
```
ambf_simulator --launch_file ~/test_ws/volumetric_drilling/launch.yaml -l 0,1
```

Let me know if you still get the Segfault.

**Comment by Jdhaworth** [comment]
That worked! Thank you!

**Comment by adnanmunawar** [comment]
Great, I already created a PR #15 for this. Will merge it very shortly.
